const SET_TITLE = 'SET_TITLE'
const SET_HEADER = 'SET_HEADER'
const SET_LOADING_STATE = 'SET_LOADING_STATE'
const SET_USER_INFO = 'SET_USER_INFO'


export {
  SET_TITLE,
  SET_HEADER,
  SET_LOADING_STATE,
  SET_USER_INFO
}